# docker-compose.yml 
version: "3.9"
services:
  synpress:
    profiles:
      - synpress
    container_name: synpress
    # Path to your Dockerfile 
    build: .
    environment:
      - DISPLAY=display:0.0
      - CYPRESS_DOCKER_RUN=true
      - CI=true
    entrypoint: []
    working_dir: /app
    # Replace "yarn test:e2e" with your test run script 
    command: > 
      yarn test:e2e:sv"
    depends_on:
      - display
    networks:
      - x11

  display:
    profiles:
      - synpress
    container_name: display
    image: synthetixio/display:016121eafdfff448414894d0ca5a50b1d72b62eb-base
    environment:
      - RUN_XTERM=no
      - DISPLAY_WIDTH=800
      - DISPLAY_HEIGHT=600
    ports:
      - "3000:3000"
    networks:
      - x11

networks:
  x11: