name: Playwright Tests
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright component tests
      run: yarn playwright test -c playwright-ct.config.ts
    - name: Run Playwright e2e tests
      run: xvfb-run yarn playwright test
      env:
        E2E_HEADLESS_MODE: false
        E2E_METAMASK_SEED_PHRASE: ${{ secrets.E2E_METAMASK_SEED_PHRASE }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
